name: Publish to GitHub Pages

on:
  push:
    branches: [master]

env:
  FLUTTER_VERSION: 3.16.5

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          baseHref: /website/